# Special Powers and Contracts Act 1885Local Act1885 No 21

Date of assent22 September 1885

## Contents

[Title][0]
    
*   [Preamble][1]

[1][2] [Short Title][2]

[2][3] [Governor may perform the several acts specified in the second column of Schedule 1][3]

[3][4] [Legal estate may be antevested][4]

[4][5] [Provision in case of land inalienable for a longer period than twenty-one years, except with consent of Governor][5] \[Repealed\]

[5][6] [Thames Harbour Board may exchange land in Schedule 2][6] \[Repealed\]

[6][7] [Vesting land at Wellington in the Governors of the Wellington College for a site for a Girls High School][7]

[7][8] [Extension of Christchurch tramway beyond the city authorised][8] \[Repealed\]

[8][9] [Income of Greymouth High School may be applied for purposes of the District High School][9] \[Repealed\]

[Schedule 1][10]  
[][10]

[Schedule 2][11]  
[][11]

---

An Act to grant certain Special Powers to the Governor to issue Crown Grants, and to enable him to carry out certain Contracts and Promises.
    
*   #### Preamble
    
    WHEREAS it is expedient and necessary to give the Governor power to issue the Crown grants, and to do, execute, and perform the several acts and things set forth in the second column of Schedule [1][10] hereto, in fulfilment of the promises and for the several reasons and purposes set forth in the first column of such Schedule:

BE IT THEREFORE ENACTED by the General Assembly of New Zealand in Parliament assembled, and by the authority of the same, as follows:---

##### 1 Short Title
    
*   The Short Title of this Act is The Special Powers and Contracts Act 1885\.

##### 2 Governor may perform the several acts specified in the second column of Schedule [1][10]
    
*   The Governor may issue such Crown grants, and do, execute, and perform the several acts, deeds, matters, and things which are specified in the second column of Schedule [1][10] hereto.
    
    All Crown grants, acts, deeds, matters, and things so issued, done, executed, or performed shall be good, valid, and effectual to all intents and purposes whatsoever, subject to the exceptions, restrictions, and qualifications in the said Schedule specified.

##### 3 Legal estate may be antevested
    
*   For the purpose of evidencing the title to any land specified in the said second column of Schedule [1][10], the Governor may, in any Crown grant issued under the authority hereof, antevest the legal estate in the grantee to such date as he thinks fit.

##### 4 Provision in case of land inalienable for a longer period than twenty-one years, except with consent of Governor
    
*   \[Repealed\]
    
    Section 4 was repealed, as from 31 March 1910, by section 431 Native Land Act 1909 (1909 No 15).

##### 5 Thames Harbour Board may exchange land in Schedule [2][11]
    
*   \[Repealed\]
    
    Section 5 was repealed, as from 1 November 1936, by section 14(1) Thames Harbour Act 1936 (1936 No 52).

##### 6 Vesting land at Wellington in the Governors of the Wellington College for a site for a Girls High School
    
*   From and after the passing of this Act the land hereinafter described---namely, all that area in the City of Wellington, containing one acre two roods thirty-nine perches and four-tenths of a perch, more or less, being Allotments one, two, three, four, and five of Section five hundred and eighty-four, Pipitea Street, and Allotment six of Sections five hundred and eighty-four and five hundred and ninety-four, and Allotments seven, eight, nine, ten, and eleven of Section five hundred and ninety-four, Moturoa Street---shall be and the same is hereby absolutely vested in and transferred to the Governors of the Wellington College for a site for the Girls' High School, established under the provisions of The Wellington College Acts Amendment Act 1878\.

##### 7 Extension of Christchurch tramway beyond the city authorised
    
*   \[Repealed\]
    
    Section 7 was repealed, as from 19 November 1907, by section [2][12] Statutes Repeal Act 1907 (1907 No 40).

##### 8 Income of Greymouth High School may be applied for purposes of the District High School
    
*   \[Repealed\]
    
    Section 8 was repealed, as from 19 November 1907, by section [2][12] Statutes Repeal Act 1907 (1907 No 40).

---

## Schedule 1

First ColumnSecond Column

AUCKLAND

1\. To authorize the transfer of the site occupied by the present Survey and Crown Lands Departments at Auckland to the Auckland University College Council, as a site for University College buildings.1\. May, on the offices at present occupied by the Survey and Crown Lands Departments at Auckland being vacated, transfer to the Auckland University College Council, as a site for University College buildings, all that piece or parcel of land being called or known as Lot No 1, Section No 12, of the City of Auckland, and containing by admeasurement 1 acre and 11 perches, more or less. Bounded on the North-west by Eden Street, 667 links; towards the North-east by Beach Road, about 183 links; towards the South-east by Lots Nos 2A, 2, and 3 of Section No 12 aforesaid, 648 links; and thence towards the South-west by Parliament Street, 133 links, to the commencing point: be all the aforesaid linkages more or less; together with any buildings or tenements erected thereon.

2\. By The Industrial School Act 1872 of the Province of Auckland, the land described in the Second Column was set apart as a site for an industrial school, for which purpose it is no longer required. It is proposed to devote it to the purpose of a site for the Auckland Girls' High School.2\. May, by notice in the _Gazette_, vest in the Education Board of the District of Auckland (being the Board charged with the administration of The [Auckland Girls' High School Act 1878][13]) all that parcel of land in the District of Auckland, situate in the Parish of Waitemata and County of Eden, containing 3 acres, more or less, being Section No 55 of the City of Auckland---bounded towards the North by Smith Street, 600 links; on the East by Howe Street, 500 links; on the South by Hopetown Street, 600 links; and on the West by Park Street, 500 links---together with the buildings thereon, as a site for the school constituted by the said [Auckland Girls' High School Act 1878][13].

3\. It being desirable to change the purpose, from a cemetery reserve to a recreation-ground, of Lot No 54, Section No 12, Suburbs of Auckland (One-Tree Hill), which cannot now be done, owing to the provisions of The Public Reserves Act 1881\.3\. May, by notice in the _Gazette_, change the purpose, from a cemetery reserve to a recreation-ground, of all that piece or parcel of land containing by admeasurement 15 acres and 30 perches, more or less, situate in the Survey District of Otahuhu, Provincial District of Auckland, being Lot No 54 of Section No 12 of the Suburbs of Auckland, Waitemata Parish. Bounded towards the North-west by Lot No 12 of Section No 12, Suburbs of Auckland, Parish of Waitemata, 1455 links; towards the North-east by Lot No 55 of section aforesaid, 1055 links; towards the South-east by a public road, 1465 links; and towards the South-west by a public road, 1173 links: be all the aforesaid linkages more or less. To be dealt with under the provisions of The Public Domains Act 1881\.

4\. It being desirable to change the purpose of Allotment No 180A of section 10, Suburbs of Auckland, which was reserved for a quarry, to a recreation ground, which cannot now be done, owing to the provisions of The Public Reserves Act 1881\.4\. May change the purpose from a quarry reserve to a recreation reserve of all that parcel of land in the Provincial District of Auckland, containing by admeasurement 2 acres 2 roods 36 perches, more or less, and known as Allotment No 180A of section 10, Suburbs of Auckland, situated in Block I, Otahuhu Survey District. Bounded towards the North by Allotments Nos 180 and 69A, 680 links; towards the East by a road, 534 links; and towards the South-west and West by a road, 163 links, 279 links, 217 links, 96 links, and 248 links: be all the aforesaid linkages more or less. To be dealt with under the provisions of The Public Domains Act 1881\.

5\. In compensation for timber taken from land the property of Wenzl Schischka, of Puhoi, in the Auckland Land District, by an arrangement made, in 1876, with the then Superintendent of the Province of Auckland.5\. May issue a Crown grant to Wenzl Schischka for Section No 13, Block III, Waiwera Survey District, containing 49 acres 2 roods. Grant to be subject to The Crown Grants Act 1883, and not to be issued until the Land Board of Auckland report to the Governor that the requirements of section 3, subsections 1 to 6, Appendix A, of The Land Act 1877 have been complied with.

6\. Certain land, a portion of which is described in the second column hereto, was taken by Proclamation dated the 13th October, 1880, for the purposes of the Kawakawa Railway, and as several valuable buildings are erected on such land, and as the land is not absolutely required for the construction of the railway, it is considered desirable to annual so much of the Proclamation as takes the land described in the second column, and to vest it in the person from whom the Government acquired it.6\. May issue a Crown grant to the person from whom the land herein described was taken by Proclamation, as mentioned in accompanying column, of all that piece or parcel of land containing by admeasurement 39 perches, being portion of Tainga Nos 2 and 3 Blocks, Nos 1172 and 1942, situate in the Parish of Ruapekapeka, Survey District of Kawakawa, Provincial District of Auckland; commencing at a point where the eastern boundary of land taken by Proclamation dated the 13th October, 1880, intersects the northern boundary of Tainga No 3 Block, No 1942\. Bounded as follows: Northerly by the northern boundary of Tainga No 3 Block aforesaid, 20 links; Westerly by lines, 266, 60, and 312 links respectively; Easterly by the eastern boundary of land taken by Proclamation as above, 280, 26, and 308 links respectively, to commencing point: be all the above areas and linkages either more or less; as the same is more particularly delineated upon the plan marked PWD 13343, deposited in the office of the Minister for Public Works, at Wellington, in the Provincial District of Wellington, and thereon coloured pink.

7\. Repealed.7\. Repealed.

8\. Allotments of confiscated lands between the River Waikato and the City of Auckland, and within the Provincial District of Auckland, having been selected for occupation and settlement, for protection of the frontier, under the terms of the New Zealand Settlements Acts, by certain persons who, in breach of their engagements, have in some cases never occupied the allotments selected by them, and in others have abandoned them for more than ten years, leaving the same waste and unimproved, it is just that the Governor should resume possession of the said lands on behalf of the Queen, and dispose of them as Crown lands.8\. May, by notification in the _Gazette_ or by advertisement in any newspaper or newspapers, or in both ways, as he shall think most suitable, not less than once in each of three consecutive months, advertise as derelict all allotments of confiscated lands within the respective Parishes of Hunua, Otau, Opaheke, Maungatawhiri, Tuakau North, Pukekoke, Puni, Waiuku, and Waipipi, all in the Provincial District of Auckland, which have been deserted for more than ten years by the persons to whom they were allotted under the terms of The New Zealand Settlements Act 1863 and the Acts amending the same; and, if within three months from the date of the last of such last-mentioned notification or advertisement neither the person to whom any such allotment was originally allotted nor his lawful representatives shall establish his claim thereto, shall, at the expiration of such last-mentioned period of three months, resume possession thereof on behalf of Her Majesty, and may at any time thereafter dispose of the same as Crown lands.

9\. Repealed.9\. Repealed.

10\. Repealed.10\. Repealed.

11\. To definitely determine the terms of, and give legal effect to, a verbal contract entered into by John Edwin Macdonald, then Mayor of the Thames Borough, with one Thomas Spencer, of Parawai, Thames, previous to the passing of The [Thames Water Supply Act 1876][14], and The [Thames Water Supply Transfer Act 1880][15], under which Acts certain plant mentioned therein became the property of, and was vested in, the Mayor, Councillors, and Burgesses of the Thames Borough; and to carry into practical effect the recommendation of the Public Petitions Committee in 1882 upon the petition of the said Thomas Spencer, and also the recommendation of the Local Bills Committee of 1885, which Committee was specially ordered by the House of Representatives to examine into and report upon the grievance set forth in the Spencer Restoration of Water Rights Bill, after it had passed its second reading.11\. The Governor may appoint some person to be a Commissioner to ascertain and determine, and to express in a writing signed by him on or before the 1st day of May, 1886, and delivered by him to the Minister of Internal Affairs of New Zealand, the terms of the said verbal contract as they would be equitably warranted by a consideration of the circumstances existing at the time of the making of such contract.

12\. The site of the old Post Office at Shortland, Thames, described in the second column, being no longer required, it is proposed to transfer the same to the Thames County Council for county offices.12\. May, by notice in the _Gazette_, vest in the Thames County Council, as a site for county offices, all that parcel of land in the Township of Shortland, Provincial District of Auckland. Bounded towards the North-east by Mackay Street, 55 feet; towards the South-east by Allotment No 433, 66 feet; towards the South-west by Allotment No 435, 55 feet; and towards the North-west by Mary Street, 66 feet, together with any buildings or tenements erected thereon.

TARANAKI

13\. Repealed.13\. Repealed.

14\. To give legal effect to promises given by the Superintendent of Taranaki in respect of the Egmont Village (Taranaki).14\. May authorize the issue of certificate of title under The Land Transfer Act 1870, and Acts amending the same, to such persons as may be in that behalf recommended in writing by the District Land Registrar of Taranaki, for Sections Nos 3 to 8, 13 to 18, 23 to 28, 33 to 38, 43 to 48, 53 to 58, 61 to 69, 71 to 79, 81 to 91, 95 to 98, 102 to 105, 109 to 112, 116 to 119, 122 to 124 (in each case inclusive), 127, 131, 132, 134, 135, 137 to 151 (inclusive), 153, 154, 156 to 158 (inclusive), 183 to 198 (inclusive), 200, and 205 on the official plan of the Egmont Village, Hua and Waiwakaiho District (Taranaki).

15\. Repealed.15\. Repealed.

16\. Repealed.16\. Repealed.

17\. Repealed.17\. Repealed.

18\. Repealed.18\. Repealed.

19\. Repealed.19\. Repealed.

20\. Repealed.20\. Repealed.

21\. Repealed.21\. Repealed.

22\. Repealed.22\. Repealed.

23\. Repealed.23\. Repealed.

HAWKE'S BAY

24\. To enable that piece of land in the Town of Clyde, Provincial District of Hawke's Bay, now known as Lambton Square, being a continuation of Clive Road, and containing 4 acres 2 roods 10 perches, to be changed to a public park and recreation-ground.24\. Notwithstanding anything contained in The Municipal Corporations Act 1876, may declare that all that piece of land in the Town of Clyde, Provincial District of Hawke's Bay, now known as Lambton Square, being in continuation of Clyde Road, and containing 4 acres 2 roods 10 perches, shall be a public park and recreation reserve, to be dealt with under the provisions of The Public Domains Act.

WELLINGTON

25\. To provide a site for an office for the Education Board of the District of Wellington.25\. May, by notice in the _Gazette_, vest in the Education Board of the District of Wellington all that parcel of land containing 15.3 perches, more or less, being Section No 3, Block III, on the plan of the Thorndon reclaimed land, Wellington, as a site for an office for the said Board; and may issue to the said Board such conveyances or assurances as may be necessary, upon the condition that if the said land should not be occupied for the said purpose within the space of five years it shall revert to the Crown.

26\. To provide a site for a school of art.26\. May, by notice in the _Gazette_, vest in the Education Board of the District of Wellington all that parcel of land containing 15.3 perches, more or less, being Section No 5, Block III, on the plan of the Thorndon reclaimed land, Wellington, upon trust, for a site for a school of art; and may issue to the said Board such conveyances or assurances as may be necessary to give effect to the arrangement hereby intended to be made, upon the condition, nevertheless, that if the said land should not be occupied for the said purpose within the space of five years it shall revert to the Crown.

27\. The land described in the second column having been purchased as a site for a drill-shed, and a drill-shed having been erected thereon, it is desirable to vest the same in Trustees, with power to mortgage, with the consent of the Governor, the said land and the buildings thereon for any term not exceeding twenty-one years.27\. May grant as a site for a drillshed and for volunteer purposes only to not less than two or more than five Trustees, for the benefit of all Volunteer corps already embodied or who may hereafter be embodied in the Hutt District, all that piece or parcel of land containing 1 rood 1 perch, more or less, being Allotments Nos 82, 84, and part of 86 on a plan deposited in the Land Registry Office, Wellington, No 101; which said land is part of Section No 5 in the public map of the Hutt District, deposited in the office of the Chief Surveyor, Wellington, and the buildings thereon. The first Trustees to be Henry Samuel Fitzherbert, Captain commanding Petone Naval Artillery Volunteers, and Peter Smith, First-class Petty Officer of the Petone Naval Artillery Volunteers, who shall have power to mortgage the land and buildings thereon for any period not exceeding twenty-one years. The Governor, by notice in the _Gazette_, shall have power to remove any Trustee from his office; and if any Trustee shall die, become bankrupt or insolvent, resign, or become incapable to act, or be absent from the Provincial District of Wellington for the space of twelve consecutive months, he shall cease to be a member of the said Trust, and the Governor may appoint another Trustee in his place. Provided always that no corps other than the Petone Naval Artillery Corps shall be entitled to the use or benefit of the said land or buildings until it shall have paid to the said Petone Naval Artillery Corps a sum of money to be agreed upon not exceeding £150, or entered into a lease with the said Petone Naval Artillery Corps agreeing to pay a rental not exceeding the sum of 20 per annum.

28\. Repealed28\. Repealed

29\. To provide funds for the acquisition of a suitable site for, and for the erection of, a hospital at Palmerston North.29\. May, by notice in the _Gazette_, authorize the Borough Council of Palmerston North to sell by public auction, after not less than three months' public notice in the land district, the under-mentioned lands, namely,--- All that piece or parcel of land in the Provincial District of Wellington, containing 3 acres 1 rood, more or less, being Allotment No 1 of Section No 167 on the plan of the Township of Palmerston North---bounded towards the North-west by Allotment No 2 of the said section, 500 links; towards the North-east by Suburban Section No 168 on the said plan, 650 links; towards the South-east by the Great Northern Road, 500 links; and towards the South-west by Terrace Street, 650 links: be all the aforesaid linkages more or less; as the same is delineated on the plan deposited in the Survey Office, Welington---which by The Palmerston North Reserves Act 1879 was authorized to be granted to the Mayor, Councillors, and Burgesses of the Borough of Palmerston North, upon trust, for the purposes or benefit of a hospital. Also Sections Nos 1530 and 1531, Block VII, Kairanga Survey District, containing by admeasurement 147 acres 2 roods, more or less---bounded towards the North-east by a road-line; towards the South-east by a road line; towards the South-west by Sections Nos. 509 and 510; and towards the North-west by Section No 1529--- which subsection 32 in the [Schedule][16] to The [Special Powers and Contracts Act 1884][17], authorized to be granted as an endowment to the Borough of Palmerston North, under the provisions of The Municipal Corporations Act 1876, and Acts amending the same. The money to be derived from the sale of the before-mentioned lands to be expended by the Borough Council in acquiring a suitable site for a hospital, and in the erection of a building thereon. May also sign and execute such instruments as may be necessary for securing a good title to the purchaser or purchasers of any of the before-mentioned lands.

NELSON

30\. The two pieces of land described in the second column having been purchased from James Costello for mining purposes, it has been deemed desirable to vest the management of the land in Trustees, for the benefit of the Charleston Hospital.30\. May, by notice in the _Gazette_, vest the management of the under-mentioned lands in three persons, to be named in such notice, namely:--- All that piece or parcel of land containing by admeasurement 79 acres 2 roods 11 perches, be the same more or less, situate in the District of Totara, being Section No 28, Square 137, on the plan of the Land District of Nelson. Also all that piece or parcel of land containing by admeasurement 51 acres and 28 perches, be the same more or less, situate in the District of Buller (Waitakere), being Section No 37, Block IV, on the plan of the Land District of Nelson. To be dealt with in manner provided by section No 59 of The Mines Act 1877\. The rents or fees to be paid over to the Charleston Hospital.

CANTERBURY

31\. The reserve described in the second column was Crown-granted to the Superintendent of the Province of Canterbury and his successors on the 27th February, 1873, in trust, as a site for a gravel-pit. It is now proposed to change the purpose of this reserve to a site for a public school, which cannot be done, owing to the provisions of The Public Reserves Act 1881\.31\. May change the purpose, from a site for a gravel-pit to a site for a public school, of all that area in the Provincial District of Canterbury, being Reserve No 1347 (in red), containing by admeasurement 5 acres, more or less, situate in the Oxford Survey District. Bounded towards the North by the Dalethorpe Road, 1400 links; towards the North-east by the Coal Tramway Reserve, 35 links; towards the South-east by a road-line, 940 links; and towards the South-west by Section No 14955, 1075 links: be all the aforesaid linkages more or less; as the same is delineated on the plan deposited in the District Survey Office, Christchurch.

32\. The reserve described in the second column was reserved as a site for a gravel-pit by the Superintendent of the Province of Canterbury, in Provincial _Gazette_ of the 9th August, 1875\. It is now proposed to change the purpose of the said reserve to a school site, which cannot be done owing to the provisions of The Public Reserves Act 1881\.32\. May change the purpose, from a site for a gravel-pit to a school-site, of all that area in the Provincial District of Canterbury, being Reserve No 1691 (in red), containing by admeasurement 5 acres, more or less, situate in the Tengawai Survey District. Bounded towards the North-east by a road-line, 500 links; towards the North-west by Section No 28224, 1002 links; towards the South-west by said section, 500 links; and towards the South-east by Section No 19197, 999 links: be all the aforesaid linkages more or less; as the same is delineated on the plan deposited in the District Survey Office, Christchurch.

33\. Repealed.33\. Repealed.

34\. Reserve No 158 (in red), situate on the south bank of the River Hurunui, was made by the Superintendent of the Province of Canterbury, in Provincial _Gazette_ of the 30th April, 1859, for the purpose of a township, but is no longer required for such purpose.34\. May, by notice in the _Gazette_, authorize the sale, under the provisions of the Land Act for the time being in force, of the under-mentioned reserve, namely, all that area of land in the Waitohi Survey District, Provincial District of Canterbury, being Reserve No 158 (in red), and containing 640 acres, more or less.

35\. Repealed.35\. Repealed.

36\. Reserve No 134 (in red), situate on the north bank of the River Waitaki, was made by the Superintendent of the Province of Canterbury, in Provincial _Gazette_ of the 22nd December, 1858, for the purpose of a township, but is no longer required for such purpose.36\. May, by notice in the _Gazette_, authorize the sale, under the provisions of the Land Act for the time being in force, of the under-mentioned reserve, namely, all that area of land in the Waitaki Survey District, Provincial District of Canterbury, being Reserve No 134 (in red), and containing 640 acres, more or less.

37\. Upon the Volunteer authorities at Timaru relinquishing all claims to part of Reserve No 204 (in red), which was set apart for a site for a drill-shed by notification published in _Gazette_ No 96, of the 20th September, 1883, and which is now reported to be unsuitable for the purpose.37\. May change the purpose, from a site for public buildings to a site to be used solely for a drillshed, of the under-mentioned parcel of land, being a portion of Reserve No 104 (in red), namely, all that parcel of land in the Provincial District of Canterbury, containing by admeasurement 1 rood 20 perches, more or less, being Sections Nos 30 and part of 31, Town of Timaru--- bounded towards the North by Grey Street; towards the East by Sections Nos 25 and 26; towards the South by the other part of Section No 31; and towards the West by the Market-place---and may vest the same in three Trustees, to be appointed by the Governor, who may remove any of the said Trustees from his office. If any Trustee shall die, become bankrupt or insolvent, resign, or become incapable of acting, or be absent from the Provincial District of Canterbury for the space of twelve consecutive months, he shall cease to be a member of the said Trust, and the Governor may, in such case, appoint another Trustee in his place.

38\. Section No 30133, on the south bank of the Rakaia River, District of Canterbury, was supposed to be Crown land available for sale, but after it was sold it was found to be included in Reserve No 1723 (in red), made for Government purposes. It is desirable, therefore, to give authority for the issue of a title to the purchaser.38\. May issue a title to the purchaser of Section No 30133, being portion of Reserve No 1723 (in red), Canterbury Land District, which was sold on the 26th November, 1877\.

39\. It being deemed desirable to change the purpose of Reserve No 1629 (in red), Town of Waimate, from an immigration depot and other public purposes to a site for a drill-shed and parade-ground, which cannot now be done, owing to the provisions of The Public Reserves Act 1881\.39\. May change the purpose, from an immigration depot and other public purposes, to a site to be used solely for a drill-shed and parade-ground, of Reserve No 1629 (in red), Town of Waimate, Provincial District of Canterbury, containing 1 acre 1 rood 14 perches, and may vest the same in three Trustees, to be appointed by the Governor, who may remove any of the said Trustees from his office. If any Trustee shall die, become bankrupt or insolvent, resign, or become incapable of acting, or be absent from the Provincial District of Canterbury, for the space of twelve consecutive months he shall cease to be a member of the said Trust, and the Governor may, in such case, appoint another Trustee in his place.

40\. It being deemed desirable to set apart as a site for a drill-shed part of Reserve No 1373 (in red), which was permanently reserved for the purpose of a public pound by the Superintendent of the Province of Canterbury, in his Proclamation dated the 18th December, 1872\. This cannot now be done, owing to the provisions of The Public Reserves Act 1881\.40\. May change the purpose, from a site for a public pound, to a site to be used solely for a drillshed, of that part of Reserve No 1373 (in red), situate in the Town of Geraldine, Provincial District of Canterbury, containing 25 perches, more or less---bounded towards the North-west by Talbot Street, 146 links; towards the North-east by the north-eastern boundary of Reserve No 1373 (in red), 95 links; towards the South-east by the south-eastern boundary of said reserve, 150 links; and towards the South-west by a line bearing 104 5′ 26″, 125 links: be all the aforesaid linkages more or less; as the same is delineated on the plan deposited in the District Survey Office, Christchurch---and may vest the same in three Trustees, to be appointed by the Governor, who may remove any of the said Trustees from his office. If any Trustee shall die, become bankrupt or insolvent, resign, or become incapable of acting, or be absent from the Provincial District of Canterbury for the space of twelve consecutive months, he shall cease to be a member of the said Trust, and the Governor may, in such case, appoint another Trustee in his place. The said Trustees to have the control and management.

The piece of land lying between Reserves Nos 1373 and 421, Town of Geraldine, and numbered 2675 (in red), has been formally set apart for an extension of the drill-shed site; and it is desirable to place it under the control of the Trustees to be appointed for managing the drill-shed site.The said Trustees also to have the control and management, for the purposes solely of a parade-ground for Volunteers, of all that parcel of land in the Provincial District of Canterbury, containing by admeasurement 32 perches, more or less, being Section No 2675 (in red), situate in the Township of Geraldine, Geraldine Survey District. Bounded towards the North-west by Talbot Street, 450 links; towards the North by Reserve No 421 (in red); towards the South-east by the continuation of the terrace forming the north-eastern and south-eastern boundaries of said reserve; and towards the South-west by Reserve No 1373 (in red), 95 links: be all the aforesaid linkages more or less; as the same is delineated on the plan deposited in the District Survey Office, Christchurch.

41\. Reserves 1815 (in red) and 1816 (in red), Provincial District of Canterbury, which were set apart for plantations, not being required for that purpose, it is deemed desirable to sell them.41\. May, by notice in the _Gazette_, authorize the sale, under the provisions of the Land Act for the time being in force, of the under-mentioned reserves, viz, Reserves 1815 (in red) and 1816 (in red).

42\. The strip of land comprised in Reserve No 1342 was reserved by the Governor, in the New Zealand Gazette of the 11th October, 1877, for the purpose of a railway-line, but is no longer required for such purpose.42\. The Governor may, by notice in the _Gazette_, authorize the sale, under the provisions of the Land Act for the time being in force, of the under-mentioned reserve, namely, all that parcel of land in the Leeston Survey District, Provincial District of Canterbury, being Reserve No 1342 (in red), containing by admeasurement 80 acres, more or less, being the strip of land, 3 chains wide, extending from the south-west boundary of Section No 7397 south-westerly to the north-east boundary of Section No 4973; as the same is delineated on the plan deposited in the District Survey Office, Christchurch: save and excepting so much of the above-described area as may be required for the purposes of public roads or tramways.

43\. The Land included in Reserve No 1251 was set apart by the Superintendent of Canterbury, in the Provincial _Gazette_ of the 5th January, 1871, for tramway or railway purposes, but it is no longer required for such purposes.43\. The Governor may, by notice in the _Gazette_, authorize the sale, under the provisions of the Land Act for the time being in force, of the under-mentioned reserve, namely, all that parcel of land in the Leeston Survey District, Provincial District of Canterbury, being Reserve No 1251 (in red), containing by admeasurement 43 acres, more or less, being the strip of land, 2 chains wide, extending from the Tramway Reserve forming the south-western boundary of Reserve No 309 (in red); southerly to the north-western boundary of Reserve No 1342 (in red): as the same is delineated on the plan deposited in the District Survey Office, Christchurch; save and excepting so much of the above-described area as may be required for the purposes of public roads.

44\. The land described in the second column adjoins the Waimate Racecourse Reserve, upon which protective works against floods have been erected at the cost of the Trustees of the Waimate Racecourse (incorporated.) It is necessary to vest the land in the Racecourse Trustees.44\. May vest in the Trustees of the Waimate Racecourse (incorporated) all that piece or parcel of land within the Waimate Survey District, Provincial District of Canterbury, commencing at a point at the south-east corner of Reserve No 2549; thence along the boundary of the racecourse in an easterly direction to the north-west corner of the Village Lot No 19; thence at right-angles to the northern boundary of said lot southerly to the reserve for creek diversion; thence along the northern boundary of said reserve westerly to a point in line with the western boundary of Lot No 1; thence westerly to the starting point. To be westerly to the starting point. To be held for the purposes mentioned in The Waimate Racecourse Reserves Act 1881\.

45\. Repealed.45\. Repealed.

46\. It being desirable to change the purpose of the land described in the second column from tramway reserves to reserves for plantation purposes, which cannot now be done, owing to the provisions of The Public Reserves Act 1881\.46\. May, by notice in the _Gazette_, declare that the purpose of the tramway reserves hereinafter described shall be changed to reserves for plantations, and vested in the Ashburton County Council. All that parcel of land in the County of Ashburton known as a tramway reserve, 200 links wide, beginning on the eastern side of the road forming the eastern boundary of Sections Nos 29599 and 24472, Alford Survey District, and running thence in a south-easterly direction to Bowyer's Stream. Also all that other parcel of land known as a tramway reserve, extending from the southern boundary of Section No 30853, Spaxton Survey District, in a north-westerly direction to the road forming the eastern boundary of Reserve No 2027, Spaxton Survey District.

OTAGO

47\. To vest in the Otago Education Board the site occupied by the Akatore Public School, the said site being part of the endowment of the Milton Athenaeum, and in exchange to vest in the Trustees of the said athenaeum a block of unoccupied Crown land. The Trustees agree to the proposed exchange.47\. May, by notice in the _Gazette_, vest in the Education Board of the District of Otago, as a school site, all that area in the Provincial District of Otago, containing by admeasurement 9 acres 2 roods 8 perches, more or less, being part of Section No 12, Block I, Akatore District; commencing at a point distant 2575.2 links west and 973.7 links north from the south-east corner of said section. Bounded thence towards the East by another part of said Section No 12, 1110 links; towards the North by another part of said section, 962.8 links; towards the West by another part of said section, 1173.2 links; and generally towards the South by a public road, 309.8 links, 66.4 links, 162.4 links, 265 links, and 398 links, 162.4 links, 265 links, and 398 links, to the commencing point: as the same is shown on a plan deposited in the office of shown on a plan deposited in the office of the Chief Surveyor, Dunedin. And may, by notice in the _Gazette_, vest in the Trustees of the Milton-Athenaeum, for the purposes of the said athenaeum, to be dealt with under the provisions of The Milton Athenaeum Reserve Act 1876, all that parcel of land in the Provincial District of Otago, containing by admeasurement 40 acres, more or less, situate in the Akatore District, and being Section No 2 of 11 of Block I of said district. Bounded towards the North by Section No 9 of same block, 1711 links; towards the East by Section No 1 of 11 of same block, 2590 links; towards the South by Section No 2 of 13 of same block, 1145 links; and towards the West and South-west by a road-line, 2600 links: be all the aforesaid linkages more or less.

48\. To give the Education Board of the District of Otago a title to the site occupied by the Leith Valley School. The land is part of a road reserve, and as such is vested in the Maori Hill Borough Council, which agrees to the proposed transfer to the Education Board.48\. May, by notice in the _Gazette_, vest in the Education Board of the District of Otago, for a school site, all that area of land in the Provincial District of Otago, containing by admeasurement 1 acre 23.7 perches, being part of a reserve for a road-line, situate to the south-east of Sections Nos 72 and 73, Block V, Dunedin and East Taieri District, commencing at peg 6 of original road traverse. Bounded thence towards the North-west by a chain-wide road, known as the Main Road, Dunedin to Waitati _via_ the Water of Leith, a distance of 326.2 links; again and finally towards the South-west, South, North-east, and North-west by other part of said road reserve, a distance of 1194.6 links, to the commencing point: be all the aforesaid linkages and area a little more or less.

49\. The two road-lines which were excluded from the endowment vested in the Borough of Alexandra, by certificate of title, Vol ii, folio 67, in the Land Transfer Office at Dunedin, dated the 29th November, 1882, being no longer required, it is desirable to vest them in the borough.49\. Notwithstanding the exception and reservation of two road-lines within the endowment of land authorized to be vested in the Borough of Alexandra, in pursuance of the terms of subsection 40 in the Schedule to The [Special Powers and Contracts Act 1881][18], may authorize the District Land Registrar at Dunedin to amend the certificate of title referred to in the first column by including the two road-lines in question as part of the borough endowment.

50\. The land described in the second column having been taken by the Government for railway purposes, and being no longer required by the Railway Department, it is desirable to reserve the same for public recreation purposes.50\. May declare the piece or parcel of land hereinafter described to be a public reserve for purposes of public recreation within the meaning of The Public Reserves Act 1881, and any Acts amending the same, namely, all that parcel of land situate in the City of Dunedin, in the Provincial District of Otago, containing by admeasurement 1 acre 3 roods 33.2 perches, more or less. Bounded as follows: Commencing at a point in the line of the western side of Cumberland Street, the said point being distant 1190 links from the south side of Stuart Street measured in a south-westerly direction along the said line of the western side of Cumberland Street; thence in a south-westerly direction, 636.4 links; thence in a south-westerly direction, 210 links; thence in a south-easterly direction, 450 links; thence in a north-easterly direction, 660 links, to the commencing point: as the same is more particularly delineated upon the plan marked PWD 13087, deposited in the office of the Minister for Public Works, at Wellington.

51\. It being desirable to change the purpose of Section 7, Block III, Waikaia, from an education reserve to a recreation-ground, which cannot now be done owing to the provisions of The Public Reserves Act 1881\. The Otago School Commissioners, in whom the land is vested, concur in the proposal.51\. May, by notice in the _Gazette_, change, from education purposes to a recreation-ground, all that parcel of land in the Provincial District of Otago, containing by admeasurement 55 acres, more or less, situate in the Waikaia District, and being Section No 7 of Block III of said district. Bounded towards the North-west by Section No 10 of same block, 1900 links; towards the North-east by Section No 1 of Block X of same district 2650 links, also by a road-line 38.8 links; towards the South-east by a road-line, 2333.7 links; and towards the South-west by a road-line, 2096 and 600 links: be all the aforesaid linkages more or less.

52\. On the 12th April, 1871, the Provincial Government of Otago purchased Section No 2 and part of Section No 1 of Block LIII, Tokomairiro District, for mining purposes. Portion of Section No 2 of said block, namely, 3 acres 39 perches, not being required for mining, it is proposed to sell it to Mrs Jane Hitchon for the sum of 6 10s.52\. May sell, in terms of section 164 of The Land Act 1877, to Mrs Jane Hitchon, and convey to her, all that piece of land containing by admeasurement 3 acres and 39 perches, more or less, situate in the Provincial District of Otago, being portion of Section No 2 of Block LIII, Tokomairiro District. Bounded towards the North-east by a road-line, 1450 links; towards the South by a road forming the northern boundary of Section No 10 of Block VII, Hillend District, 800 links; towards the West by Section No 3 of Block LIII, Tokomairiro District, 1300 links: be all the aforesaid linkages more or less; save and excepting a road-line, 100 links wide, intersecting the said area.

53\. Repealed.53\. Repealed.

54\. It being desirable to change the purpose of the Cemetery Reserve at Outram, in which no burials have taken place, to a reserve for municipal purposes.54\. May, by notice in the _Gazette_, change the purpose of all that parcel of land in the Provincial District of Otago, containing by admeasurement 4 acres 2 roods, more or less, situate in the Town of Outram, and being Sections Nos 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, and 18 of Block X of said town---bounded towards the North-west by Beaumaris Street, 1000 links; towards the North-east by Taieri Terrace, 508 links; towards the South-east by Orme Street 707 links, also by Section No 1 of same block 200 links; and towards the South-west by Sections Nos 19, 20, and 1 of same block 375 links, also by Bidston Street 125 links: be all the aforesaid linkages more or less---from a cemetery to a reserve for municipal purposes; and may vest the same in the Outram Town Board as an endowment in aid of the Town Board funds.

55\. The road described in the second column, which was declared by Order in Council issued on the 23rd July, 1878, to be a Government road, being no longer required as a road, and there being legal difficulties which prevent it being closed under the provisions of The Public Works Act 1882, so as to enable it to be leased to the Shag Point Coal Company.55\. Notwithstanding the provisions of The Public Works Act 1882, may, by notice in the _Gazette_, declare that the following road shall be closed, namely, all that parcel of land in the Provincial District of Otago, being a road-line, 1 chain in width, in the Moeraki Survey District, bounded towards the North by a road-line; towards the East by the ocean; towards the South by a coal reserve; and towards the West by Sections Nos 58, 2 of 60, and 1 of 20, Block III of said district, also by Sections Nos 45 and 42 of Block IX. And after the issue of such notice may include the aforesaid area in any lease or leases which may be issued under the provisions of clause 60 in the Schedule to The [Special Powers and Contracts Act 1884][17].

56\. Subsection [58][16] of the Schedule to The [Special Powers and Contracts Act 1884][17] authorizes the issue of a title to the Borough of Hampden for 150 acres, being part of Block I, Otepopo Survey District, therein described as a site for a commonage for the use of the inhabitants of the Borough of Hampden. The title has accordingly issued for a number of sections as surveyed, exclusive of the road-lines through the block which are no longer required. It is accordingly deemed expedient to vest the road-lines in the borough, and to authorize the Borough Council to make such regulations or by-laws as may be desirable for the use of the land as a commonage.56\. May grant to the Corporation of the Borough of Hampden the road-lines which are no longer required within the block of 150 acres of land described in subsection [58][16] of the Schedule to The [Special Powers and Contracts Act 1884][17]. The road-lines to be held in trust, with the sections which have already been vested in the borough, as a site for a commonage for the use of the inhabitants of the Borough of Hampden; and may also, by warrant under his hand, authorize the Mayor, Councillors, and burgesses of the Borough of Hampden to make such regulations and by-laws for the use of the commonage and for the payment of such fees as may be deemed expedient. The proceeds accruing from the commonage to be devoted to fencing, grassing, or otherwise improving the land; any balance of proceeds to be deemed revenue of the borough.

57\. To give effect to the recommendation of the Public Petitions Committee on the petition of William Agnew, 30th June, 1885\.57\. In addition to the sum of $100 paid to William Agnew, may grant him a title, under the Land Transfer Act without further cost, to Sections Nos 8 and 10, Block III, Blackstone Survey District, which were held by him under agricultural lease.

58\. The old cemetery site at Fortrose, Provincial District of Otago, described in the second column, having been found unsuitable for the purpose, it is deemed desirable to sell the portion of the same in which no interments have been made. A new cemetery has been provided in a more suitable position.58\. May authorize the sale, as a village settlement, under the provisions of the Land Act for the time being in force, of all that parcel of land in the Provincial District of Otago, containing by admeasurement 6 acres 1 rood 8 perches, more or less, situate in the Toitois District, and being Section No 8 of Block VIII of said district. Bounded towards the North-west by Crown lands, 700 links; towards the North-east by Section No 2 of Block IV, Town of Fortrose, 900 links; towards the South-east by Section No 18 of Block VIII, Toitois District, 700 links; towards the South-west by Sections Nos 1, 6, 7, and 8 of Block VIII, Town of Fortrose, 900 links: be all the aforesaid linkages more or less; and exempting from the above area 1 rood (so as to include present interments), to be defined by surveyor.

59\. The land described in the Schedule to The Port Chalmers Drill-shed Act 1881, which has been vested in Trustees for a drill-shed and other buildings connected with Volunteer purposes, being found unsuitable for the purpose, and other lands more suitable having been acquired out of public moneys, and become vested in Her Majesty, it is desired to transfer the last-mentioned lands to the aforesaid Trustees, in substitution of the first-mentioned lands.59\. May convey to the Trustees mentioned in The Port Chalmers Drill-shed Act 1881, upon the trusts and for the purposes mentioned in the said Act, and subject to all the provisions thereof, all that parcel of land, the property of Her Majesty the Queen, in the Town of Port Chalmers, being part of Sections Nos 54 and 55 thereof, containing by admeasurement 14.6 perches, more or less. Bounded as follows: Commencing at a point on the follows: Commencing at a point on the north-western side of George Street, 50 links distant in a north-easterly direction from the southern corner of Section No 55; thence towards the South-east by George Street, 60.6 links; thence towards the North-east by a right line parallel to the north-eastern boundary of Section No 55, 151.5 links; thence towards the North-west by a right line parallel to George Street, 60.6 links; and thence towards the South-west by a right line parallel to the said north-eastern boundary of Section No 55, 151.5 links, to the point of commencement; as the same is delineated on the plan in the Survey Office, Dunedin: upon receiving from the aforesaid Trustees a deed of surrender to Her Majesty of the lands described in the Schedule to the Act hereinabove last mentioned; and may sell the lands so surrendered by public auction.

60\. The Government Land Purchase Officer (Mr Calcutt) agreed, on behalf of the Government, with James Fletcher, of Port Chalmers, shipwright, that the said James Fletcher should convey to Her Majesty the Queen Allotment No 149 and parts of Allotments Nos 150 and 151 on the map of the private Township of Mansford, in the Provincial District of Otago, containing 2 roods 11 perches, in exchange for part of the adjoining Allotments Nos 108 and 109, Township of Mansford aforesaid, containing 1 rood 10.5 perches, which have been acquired by Her Majesty under the Public Works Acts for railway purposes. The said James Fletcher conveyed to the Queen, with other lands, the said Allotment No 149 and part of Allotments Nos 150 and 151, but has never received a conveyance for part of the said Allotments Nos 108 and 109\.60\. May convey to James Fletcher, of Port Chalmers, shipwright, all that piece of land in the Provincial District of Otago, the property of Her Majesty, situate in the private Township of Mansford, containing 1 rood 10.5 perches, more or less, being part of Allotments Nos 108 and 109 on the plan of the said township. Bounded towards the North-west by Coombe Hay Terrace, 182 links; towards the East by other parts of said Allotments Nos 108 and 109, 309.7 links; towards the South-east by Allotment No 150, 45.5 links; and towards the South-west by Allotment No 107, 278 links.

61\. The Government Land Purchase Officer (Mr Calcutt) agreed, on behalf of the Government, with Robert Grigor, of Balclutha, the agent acting on behalf of the devisees of the late Frederick Ludlow, to exchange Section No 16, Block X, Town of Balclutha (which has been acquired by Her Majesty under the Public Works Acts for railway purposes), for Section No 17, Block X, Town of Balclutha aforesaid. the property of the late Frederick Ludlow.61\. May convey to the trustees acting under the will of the late Frederick Ludlow, upon the trusts of the said will, Section No 16, Block X, Town of Balclutha, the property of Her Majesty, upon the said trustees and all other necessary parties conveying to Her Majesty the Queen Section No 17, Block X, Town of Balclutha aforesaid.

62\. Section No 24, Block I, Invercargill Hundred, which was Crown-granted to the Superintendent of Southland for a lunatic asylum reserve, being no longer required for that purpose, it is desirable that it should be made an endowment for the Borough of Gladstone.62\. May, by notice in the _Gazette_, declare that all that parcel of land in the Southland Land District, containing by admeasurement 10 acres, more or less, being Section No 24, Block I, Invercargill Hundred---bounded towards the North by original Section No 25 of said block, 1026 links; towards the East by original Section No 23 of said block, 974 links; towards the South by Section No 22 of said block and by a road-line, 1026 links; and towards the West by original Section No 29 of said block, 974 links--- shall cease to be a lunatic asylum reserve, and may grant such land to the Corporation of the Borough of Gladstone as an endowment for the said borough.

63\. It being desirable to increase the area of the land vested in the Tokomairiro Farmers' Club by The [Tokomairiro Farmers' Club Act 1877][19], for the purposes of a show-ground.63\. May, by notice in the _Gazette_, change the purpose, from police purposes to an agricultural show-ground, of all that parcel of land in the Provincial District of Otago, containing by admeasurement 2 acres and 10 perches, more or less, situate in the Tokomairiro District, and being part of original Section No 104 of Block XII of said district. Bounded towards the North-west by other part of said Section No 104, 200 links; towards the North-east by other part of said section, 1032 links; towards the South-east by the Main South Road, 200 links; and towards the South-west by the Tokomairiro Farmers' Club Reserve, 1032 links: be all the aforesaid linkages more or less. And upon the issue of the said notice the land described shall vest in the Trustees of the Tokomairiro Farmers' Club, incorporated under The [Tokomairiro Farmers' Club Reserve Act 1877][19].

64\. The land described in the second column being no longer required for the purpose for which it was purchased by the Superintendent of Otago, it is desirable to change the purpose of it to a recreation-ground.64\. May, by notice in the _Gazette_, change the purpose, from a reserve for police purposes to a recreation-ground, of all that parcel of land in the Provincial District of Otago, containing by admeasurement 49 acres 2 roods 30 perches, more or less, situate in the Tokomairiro District, and being parts of Sections Nos 103 and 104 of Block XII of said district. Bounded towards the North-west by parts of Sections Nos 111 and 112 of same block and district, 2998 links; towards the North-east by Section No 105 of same block, 40 links and 3333 links; towards the South-east by the Main South Road 563 links, by the Tokomairiro Farmers' Club Reserve, including recent addition, 600 links, also by the main south line of railway 1780 links; towards the South-west by the Tokomairiro Farmers' Club Reserve 1032 links, by part of said Section No 103 1900 links, also by part of the Township of Milton 1200 links: be all the aforesaid linkages more or less; and intersected through that portion of Section No 104 (now being described) by the main south line of railway about 90 links wide. As an addition to the Tokomairiro Recreation-ground, to be dealt with under The Public Domains Act 1881\.

SOUTHLAND

65\. It being desirable that Sections Nos 22 and 23, Block VII, Invercargill Hundred, which were Crown-granted to the Superintendent of Southland on the 31st January, 1870, for purposes connected with a market, should be sold as village-settlement land.65\. May, by notice in the _Gazette_, declare that Sections Nos 22 and 23, Block VII, Invercargill Hundred, may be sold as small-farm allotments, on such conditions as may be prescribed by Order in Council to be issued under the provisions of the Land Act for the time being in force.

66\. The Trustees appointed by The Mataura Reserves Act 1878, for the Recreation Reserve and site set apart for the Mataura Pastoral and Agricultural Society having resigned, it is desirable that both pieces of land should be managed by the Town Board of Mataura.66\. Notwithstanding anything contained in The Mataura Reserves Act 1878, may, by notice in the _Gazette_, declare the following land to be subject to the provisions of The Public Domains Act 1881, namely, Section No 13, Block XII, Town of Mataura, containing 4 acres 3 roods 34 perches, as described in the Second Schedule to The Mataura Reserves Act 1878, to be managed by the Mataura Town Board under a delegation, in terms of the 12th section of The Public Domains Act 1881, aforesaid; and may also, in pursuance of the provisions of The Public Reserves Act 1881, vest the following land in the Town Board aforesaid, in trust for the Mataura Pastoral Society, namely, Section No 14, Block XII, Town of Mataura, containing 5 acres 1 rood 34 perches, as described in Schedule 3 to The Mataura Reserves Act 1878\.

67\. It being deemed desirable that Reserved Sections Nos 27 to 31, Block VII, East Winton, 46 acres and 12 perches, being part of a gravel reserve, as per Otago Gazette of the 7th October, 1874, page 360, should be sold as suburban deferred-payment land.67\. May sell 46 acres and 12 perches, more or less, being Sections Nos 27 to 31, Block VII, East Winton, as suburban deferred-payment allotments, under the Land Act for the time being in force.

WESTLAND

68\. Repealed.68\. Repealed.

*   Clauses 7, 9, 13, 15 to 23, 33, 35, 45 and 68 were repealed, as from 19 November 1907, by section [2][12] Statutes Repeal Act 1907 (1907 No 40).
*   Clause 10 was repealed, as from 31 March 1910, by section 431 Native Land Act 1909 (1909 No 15).
*   Clause 22 was repealed, as from 29 October 1906, by section 3 Waimate Agricultural Reserve Dairy School Act 1906 (1906 No 38).
*   Clause 28 was repealed, as from 16 September 1889, by section [31][20] Masterton Trust Lands Act 1889 (1889 No 13(L)).
*   Clause 53 was repealed, as from 26 September 1912, by section [5(3)][21] Agricultural and Pastoral Societies Amendment Act 1912 (1912 No 7).

## Schedule 2

AUCKLAND

1\. Before the Thames foreshore became vested in the Thames Harbour Board, the Board had agreed with William Rowe to exchange a piece of land on the foreshore, to enable the Board to construct a road along the beach in a straight line, and to give to Mr Rowe a frontage for his allotments to the proposed road. By The Thames Harbour Board Act 1878, all such arrangements should have been settled by a Judge of the High Court, but when the Judge sat for the purpose of hearing such claims Mr Rowe omitted to put in his claim.1\. All that piece or parcel of land containing 21.5 perches, be the same a little more or less, being part of the Thames foreshore, situate in the Borough of Thames. Bounded towards the North and East by part of Tekaraka Block, being the line of high-water mark, 100, 30, and 135 links; towards the South by a continuation of Walters Street, 61.5 links; and towards the West by other part of the Thames foreshore, 132, 27.3, and 72.5 links: be the said several measurements a little more or less; excepting out of the above piece of land that portion thereof, containing 2.8 perches, occupied by the Karaka Creek, and now used as a public drain. Also all that piece or parcel of land containing 13.6 perches, be the same a little more or less, being part of the said Thames foreshore. Bounded towards the North by the continuation of Walters Street, 51.5 links; towards the East by Tekaraka Block, being the line of high-water mark, 189 links; towards the South by part of the Thames foreshore, 39 links; and towards the West by part of the Thames foreshore, 188.7 links: be all the said several measurements a little more or less. The said land is coloured yellow on plan marked MD 1054, and deposited in the office of the Marine Department, Wellington.

*   The reference to the High Court was substituted, as from 1 April 1980, for a reference to the Supreme Court pursuant to section [12][22] Judicature Amendment Act 1979 (1979 No 124).



[0]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18765
[1]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18766
[2]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18769
[3]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18770
[4]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18771
[5]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18772
[6]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18774
[7]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18776
[8]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18777
[9]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18779
[10]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18781
[11]: http://www.legislation.govt.nz/act/local/1885/0021/latest/whole.html#DLM18791
[12]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM136296
[13]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM14574
[14]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM12368
[15]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM15137
[16]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM17719
[17]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM17704
[18]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM15559
[19]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM13133
[20]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM21598
[21]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM178561
[22]: http://www.legislation.govt.nz/act/local/1885/0021/latest/link.aspx?id=DLM35049